add security blurb to readme
Azure-Samples/azd-template-artifacts pull request #10
Opened 2024-05-06 20:39 UTC by gkulin

2024-05-06 21:11 UTC, kristenwomack requested changes
Overall this is great, do we want to be firmer about security? I made a suggestion. And you could add, "we recommend this for your repos, as well?" - what do you think?

2024-05-06 21:11 UTC, kristenwomack commented on README.md
> +
```suggestion
To be secure by design, we require templates in any Microsoft template collections to have the [Github secret scanning](https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning) setting is enabled in your repos.'
```

2024-05-06 21:11 UTC, kristenwomack commented on README.md
> +
Do we want more firm requirements here?

2024-05-07 16:06 UTC, gkulin commented on README.md
> +
resolving after we discussed offline

2024-05-07 17:57 UTC, kristenwomack approved these changes
LGTM

2024-05-07 17:59 UTC, merged