add azd services to functional req checklist
Azure-Samples/azd-template-artifacts pull request #20
Opened 2024-09-06 01:53 UTC by kristenwomack

Add azd services in the `azure.yaml` file as part of the functional requirements.

2024-09-10 12:47 UTC, anfibiacreativa requested changes

2024-09-10 12:47 UTC, anfibiacreativa commented on checklist.md
> +- [ ] **azure.yaml** - `azure.yaml` file is in place and services are configured for azd
```suggestion
- [ ] **azure.yaml** - `azure.yaml` file is in place and services are configured for azd. Find the schema and examples in [this link](https://learn.microsoft.com/azure/developer/azure-developer-cli/azd-schema)
```

2024-10-10 12:00 UTC, anfibiacreativa commented
This PR is no longer valid, since the file was removed. 
@kristenwomack would you like to apply the changes to DoD?

2024-10-10 12:00 UTC, closed without merging

2024-10-10 12:24 UTC, kristenwomack commented
> This PR is no longer valid, since the file was removed. @kristenwomack would you like to apply the changes to DoD?

yes, that's a good idea. do you want me to do it or are you already on it?